base_url: "http://localhost:8080"
auth_token: "eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJleGFtcGxlMzNAZXhhbXBsZS5jb20iLCJpYXQiOjE3NjQ1Mjc0MTgsImV4cCI6MTc2NDYxMzgxOH0.D2NLz8PhD3lMwjid8BlpPKIz8TSiHhIg1ZLUjTMLbuO0nMpGbgoblSnuFXgHr_rmc7VH88j3Wv64fIhiW2Pdtg"
account_id: 2
admin_token: "eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJleGFtcGxlMkBleGFtcGxlLmNvbSIsImlhdCI6MTc2MzkxMTg4NCwiZXhwIjoxNzYzOTk4Mjg0fQ.Z6GHMG7H2h0Zd0ktS4iefJS_dZ5uK2ANJGzX9mUIiTalkK7xJOJfaCgaOsmwdl-Aof1rFQSPY3TxltBpz2KPug"
