base_url: "http://localhost:8080"
auth_token: "eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZG1pbkB0ZXN0LmNvbSIsImlhdCI6MTc2NTgyMjI5MywiZXhwIjoxNzY1OTA4NjkzfQ.aizQNmjNZz5qoEkSBd_Ksi8_wXVC0eq76xIGY1sEOvFImPVBRvpzfPmTQyu3nm08QBGcpHEaRnkxgCK4zubOyQ"
account_id: 4
admin_token: "eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZG1pbkB0ZXN0LmNvbSIsImlhdCI6MTc2NTgyMjI5MywiZXhwIjoxNzY1OTA4NjkzfQ.aizQNmjNZz5qoEkSBd_Ksi8_wXVC0eq76xIGY1sEOvFImPVBRvpzfPmTQyu3nm08QBGcpHEaRnkxgCK4zubOyQ"
